apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: reactive-demo-deployment
spec:
  selector:
    matchLabels:
      app: reactive-demo-mysql
  replicas: 3 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: reactive-demo-mysql
    spec:
      containers:
        - name: reactive-demo
          image: marvgm/reactive-demo:1.0.2 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster
          env: # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              value: mysql
            - name: DB_NAME  # Setting Database name from configMap
              value: javatechie
            - name: DB_USERNAME  # Setting Database username from Secret
              value: root
            - name: DB_PASSWORD # Setting Database password from Secret
              value: root
---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: reactive-demo-svc
spec:
  selector:
    app: reactive-demo-mysql
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.
