apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: reactive-demo
spec:
  selector:
    matchLabels:
      app: reactive-demo
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: reactive-demo
    spec:
      containers:
        - name: reactive-demo
          image: marvgm/reactive-demo:1.0.0 # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster